app/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
app_name = "app"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('donate/', views.donate, name="donate"),
    path('events/', views.event, name="events"),
    path('volunteer/', views.volunteer, name="volunteer")
]

apply/urls.py
from django.urls import path
from . import views

app_name = "apply"
urlpatterns = [
    path('apply/', views.apply, name="apply"),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('', include('apply.urls'))
]

apply/models.py
from django.db import models
from django.core.validators import EMPTY_VALUES, validate_email
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
GENDER_CHOICES = [
    ('space', ''),
    ('male', 'Male'),
    ('female', 'Female'),
    ('nonbinary', 'Nonbinary'),
    ('other', 'Other')
]

GRADE_CHOICES = [
    (None, 'Choose a Grade'),
    ('FR', 'Freshman'),
    ('SO', 'Sophomore'),
    ('JR', 'Junior'),
    ('SR', 'Senior')
]
DAYS = []
YEARS = []
for i in range(1, 32):
    DAYS.append((str(i), str(i)))

for i in range (1920, 2022):
    YEARS.append((i, i))

MONTHS = [
    ('None', ' '),
    ('january', 'January'),
    ('february', 'February'),
    ('march', 'March'),
    ('april', 'April'),
    ('may', 'May'),
    ('june', 'June'),
    ('july', 'July'),
    ('august', 'August'),
    ('september', 'September'),
    ('october', 'October'),
    ('november', 'November'),
    ('december', 'December'),

]
print(YEARS)
# Create your models here.
class Applicant(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100, validators=[validate_email])
    phone = models.DecimalField(max_digits=10, decimal_places=0)
    gender = models.CharField(max_length=100, choices=GENDER_CHOICES, default=None, blank=False)
    grade  = models.CharField(max_length=100, choices=GRADE_CHOICES, default=None, blank=False)
    school = models.CharField(max_length=100, blank=True)
    birthday = models.CharField(max_length=30, choices=DAYS, default=None, blank=True)
    birthmonth = models.CharField(max_length=30, choices=MONTHS, default=None, blank=True)
    birthyear = models.IntegerField(default=None, choices=YEARS, blank=True)
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    county = models.CharField(max_length=100, default=None)
    zip_code = models.IntegerField()
    check = models.BooleanField(default=False)
    readCheck = models.BooleanField(default=False)

    
    
    def __str__(self):
        return self.first_name + " " + self.last_name


            
       

apply/forms.py
from django.forms import ModelForm
from .models import Applicant
from django.utils.translation import ugettext_lazy as _


class ApplicantForm(ModelForm):
    class Meta:
        model = Applicant
        fields = '__all__'
  
        
        
        

apply/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import ApplicantForm
import smtplib
from email.message import EmailMessage
from django.contrib import messages

# Create your views here.


def apply(request, template="apply.html"):
    form = ApplicantForm()
    if request.method == 'POST':
        form = ApplicantForm(request.POST)
    
        if form.is_valid():
            form.save()
            messages.success(request, 'Your application has been submitted! Check your email for more information.')
            msg=EmailMessage()
            msg['Subject'] = 'Junior Hands Association Confirmation'
            msg['From'] = "Junior Hands Assocation"
            msg['To'] = form.cleaned_data['email']
            msg.set_content(" Test Email JHA " )
            
            server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
            server.login("thejuniorhands@gmail.com", "handsbick2021")
            server.send_message(msg)
            server.quit() 
            
            return HttpResponseRedirect(request.path_info)
        
    print(form.errors.as_data())
    return render(request, template, {'form': form})

app/templates/about.html
{% extends 'base.html' %}
{% block title %}JHA - About{% endblock %}
{% block content %}

<div class="heading">
    <h1>ABOUT US</h1>
    <h2 class="motivation">Fostering a better educational environment through student-driven activism.</h2>
   
</div>
<h1 class="we-title">What We Do?</h1>
<section class="we-do">
    
    <div>
        <div>
            <a href="{% url 'app:home' %}#weare">
                <img src="../static/kentucky.png" alt="kentucky">
            </a>
        </div>
     
        <p>We are an association based in Louisville, Kentucky </p>
    </div>
    <div>
        <div>
            <a href="#ms">
                <img src="../static/scholar.png" alt="scholar">
           </a>
          
        </div>
       
        <p>We aim improve the educational environment for everyone</p>
    </div>
    <div>
        <div>
            <a class="nodis" href="#sup">
                <img src="../static/nodiscrim.png" alt="no-discrim">
            </a>
          
        </div>
      
        <p>We seek to serve our community without discrimination</p>
    </div>
    <div>
        <div>
            <a class="youth" href="#sup">
                <img src="../static/student.png" alt="student">
            </a>
          
        </div>
       
        <p>We strive through student organized activism </p>
    </div>
    
</section>
<section class="sup-parent" id="sup"> 
    <h1 class="sup-title">Supporting Our Community</h1>
    <section class="drop-button">
        <h3>Our Committment To The Youth</h3>
        <i class="fas fa-grip-lines"></i>
    </section>
    <article class="text-hid">
        <p>“The future of the world belongs to the youth of the world, 
            and it is from the youth and not from the old that the fire of life
            will warm and enlighten the world. It is your privilege to breathe the 
            breath of life into the dry bones of many around you.” - Tom Mann
        </p>
        <p>
            Support for the youth is the foundation on which the ideals of the 
            Junior Hands Association were built upon. The Junior Hands Association 
            firmly believes in the new generation of leaders and their ability to tackle 
            the grave pitfalls of modern society. We aim to tackle the deep seated roots of 
            oppression and maltreatment but we can’t do it without the next generation. It is
            only with their help that we can start to break and claw at the never-ending waves 
            of unfairness and inequality that’re ever so present throughout our communities. 
            Without the shining light and passion that all of the youth share together our 
        </p>

        <p>With all that being said it is with great pride that we pronounce our unwavering commitment to the youth and all the hopes and dreams that stand beside them. </p>
    </article>
    <section class="drop-button2" id="youth">
        <h3>Our Commitment To Marginalized Groups</h3>
        <i class="fas fa-grip-lines"></i>
    </section>
    <article class="text-hid2">
        <p>Unfortunately, many of the youth we serve belong to marginalized communities. These are communities that our society and governments have cast aside or deemed unworthy of attention. But it is in these very communities that the youth with the most potential reside. In order to provide more to those in need, we made the decision that all of our programs and opportunities be free of charge and open to all members of society, regardless of where they come from. Our organization is committed to providing an equal chance to all youth. 

        </p>
    </article>
</section>
<div class="ms" id="ms" >
    <article>
        <h2>Vision Statement</h2>
        
        <p>The Junior Hands Association is a student-led organization that prides 
            itself in fostering a better environment for education. We provide 
            opportunities for high school students across Kentucky to connect with 
            their communities and improve the lives of their fellow peers. Volunteers 
            are encouraged to utilize their unique skill sets to better serve systematically 
            disadvantaged communities. By emphasizing student-driven activism, we hope to 
            improve the leadership, critical thinking, and creativity of our volunteers. With 
            the goal of improving the situations that impair education, we hope to forge a more 
            prepared generation of capable citizens.
        </p>
    </article>
    <div>
        <img src="../static/whiteflag.png" alt="flag" height="50" width="50">
    </div>
</div>
<div class="apply-parent" id="app-sec">
    <section class="app-sec">
        <div class="app-sec-right">
            <div >
            <h1>Becoming a member is only one click away</h1>
            </div>
            <p style="margin: 1em 0 2em 0;">Applying allows you to become eligible to volunteer and organize JHA events</p>
            
            <div class='app-btn-parent'>
                <form>
                    <button formaction="{% url 'apply:apply' %}" >Apply</button>
                </form>
                
            </div>

        </div>
        <img src="../static/redtree.png" />
    
    </section>
</div>










{% endblock %}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="../static/css/base.css">
        <link rel="stylesheet" type="text/css" href="../static/css/about.css">
        <link rel="stylesheet" type="text/css" href="../static/css/contact.css">
        <link rel="stylesheet" type="text/css" href="../static/fontawesome/css/all.min.css">
        <link rel="stylesheet" type="text/css" href="../static/css/apply.css">
        <link rel="stylesheet" type="text/css" href="../static/css/donate.css">


     

    </head>
    <body >
        <!-- Nav Bar -->
        <header>


            <nav class="navbar_">
                
                <div class="logo">
                        <img src="../static/whitered2.png" alt="logo" width="60" height="60" class="logo-img" />
                        <h1>Junior Hands Assocation </h1>
                </div>
                
                <div class="hamburger">
                    <div class="line"></div>
                    <div class="line"></div>
                    <div class="line"></div>
                </div>
                <ul class="nav-links">
                    <li><a href="{% url 'app:home' %}"
                        {% if request.path == "/" %}
                        class="current"
                        {% endif %}>Home</a></li>
                    <li><a href="{% url 'app:about' %}"
                        {% if request.path == "/about/" %}
                        class="current"
                        {% endif %}>About</a></li>
                    <li><a href="{% url 'app:contact' %}"
                        {% if request.path == "/contact/" %}
                        class="current"
                        {% endif %}>Contact</a></li>
                    <li><a href="{% url 'app:donate' %}"
                        {% if request.path == "/donate/" %}
                        class="current"
                        {% endif %}>Donate</a></li>
                    
                    
                </ul>
            </nav>
        </header>
        <div id="content", name="content">
            {% block content %}
            {% endblock %}
        </div>

            
 
          <footer>

          
            <section class="contacts">
                
              <a href="https://www.instagram.com/thejuniorhands/" target="_blank"><img src="../static/insta.png" width="55" height="55" alt="insta"></a>
              <a href="https://twitter.com/thejuniorhands" target="_blank"><img src="../static/twitter.png" width="55" height="55" alt="twitter"></a>
              <a href="https://www.facebook.com/Junior-Hands-Association-102088245579172" target="_blank"><img src="../static/facebook.png" width="55" height="55" alt="facebook"></a>
 
            </section>
            <section class="links">
              <a href="{% url 'app:home' %}">HOME</a>
              <a href="{% url 'app:about' %}">ABOUT</a>
              <a href="{% url 'app:contact' %}">CONTACT</a>
           
            </section>
            <section class="section-links">
                <a href="{% url 'app:home' %}#upcoming">Upcoming</a>
                <a href="{% static 'By-laws.pdf' %}" target="_blank">By Laws</a>
                <a href="{% url 'app:contact' %}#emailus">Email</a>
                <a href="{% url 'apply:apply' %}">Apply</a>
            </section>
            <button> <a href ="#" >Donate </a></button>


           
        </footer>
       

    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script>

        $(window).scroll(function(){
            if($(window).scrollTop() ){
                $("nav").addClass("sticky");
                $("a.current").addClass("current-2")
            }
            else{
                $("nav").removeClass("sticky");
                $("a.current").removeClass("current-2")


            }
        })
    </script>
    <script>
        const hamburger = document.querySelector('.hamburger');
        const navLinks = document.querySelector('.nav-links');
        const links = document.querySelectorAll('.nav-links li');
        const logo = document.querySelector('.logo')
             hamburger.addEventListener('click', () => {
                 navLinks.classList.toggle('open');
                 logo.classList.toggle('open');
             })
   </script>    
  <script>
      const nodis = document.querySelector('.nodis');
      const dropButton = document.querySelector('.drop-button');
      const hidText = document.querySelector('.text-hid');
      const icon = document.querySelector('.drop-button i');
      let name = hidText.className;
        dropButton.addEventListener('click', ()=> {
                hidText.classList.toggle('visible');
                dropButton.classList.toggle('drop-clicked');
                icon.classList.remove('rotate');
                icon.offsetWidth;
                icon.classList.add('rotate');
        })
        nodis.addEventListener('click', ()=> {
                if (!(name.includes('visible'))){
                    hidText.classList.toggle('visible');
                    dropButton.classList.toggle('drop-clicked');
                    icon.classList.remove('rotate');
                    icon.offsetWidth;
                    icon.classList.add('rotate');
                }
        })
        
  </script>
  <script>
      const youth = document.querySelector('.youth');
      const dropButton2 = document.querySelector('.drop-button2');
      const hidText2 = document.querySelector('.text-hid2');
      const icon2 = document.querySelector('.drop-button2 i');
        dropButton2.addEventListener('click', ()=> {
                hidText2.classList.toggle('visible');
                dropButton2.classList.toggle('drop-clicked');
                icon2.classList.remove('rotate');
                icon2.offsetWidth;
                icon2.classList.add('rotate');
               
                
        })
        youth.addEventListener('click', ()=> {
                hidText2.classList.toggle('visible');
                dropButton2.classList.toggle('drop-clicked');
                icon2.classList.remove('rotate');
                icon2.offsetWidth;
                icon2.classList.add('rotate');
        })
  </script>
    </body>
</html>

app/templates/contact.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}JHA - Contact{% endblock %}
{% block content %}

<h1 class="contact-us">Contact Us</h1>
<p class="contact-message-sub">Share your <span class="accent">thoughts</span>, <span class="accent">ideas</span>, or <span class="accent">opinions</span></p>
<div class="contact-body">
   
    
        
</div>
<h1 class="contact-message-header">We Need <span style="color:rgb(255, 81, 81);">Feedback!</span></h1>
<p class="contact-message">In order to impact the community, we need to hear from you.</p>

<div class="contact-section-parent" id="emailus">
    <form class="contact-form" action="" method="POST">
        <h1 class="contact-title">Quick Contact</h1>
        {% csrf_token %}
        <p>Your data will not be stored in any databases after your message has been sent.</p>
        <h1>Full Name</h1>
        <section>

            <div>
                {{ form.firstName|add_class:"c-name"|attr:"placeholder: Ex. John" }}
                <label>First</label>
            </div>
            <div>
                {{ form.lastName|add_class:"c-name"|attr:"placeholder: Ex. Smith" }}
                <label>Last</label>
            </div>
            
        </section>
        <h1>Email</h1>
        {{ form.email|attr:"placeholder: Ex. email@example.com" }}
        <h1>Subject</h1>
        {{ form.subject|attr:"placeholder: Ex. Event Opportunity" }}
        <h1>Message</h1>
        {{ form.message|attr:"placeholder: Ex. My Message" }}
        
        
        <input class="contact-btn" type="submit" value="Send Message">
        {% if messages %}
        <div class="alert alert-success" role="alert" style="width: 20em;margin: 0 auto;text-align:center;">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
        {% endif %}
    </form>
    <div class="contacts-col">
        <h2>Find Us</h2>
        <section>
            <i class="far fa-paper-plane fa-3x"></i>
            <h1>Email</h1>
            <p>thejuniorhands@gmail.com</p>

        </section>
        <section>
            <i class="fas fa-phone-alt fa-3x"></i>
            <h1>Phone</h1>
            <p>502-240-9793</p>
            
        </section>
        <section>
            <a href="https://www.instagram.com/thejuniorhands/" target="_blank"><i class="fab fa-instagram fa-4x"></i></a>
            <h1>Instagram</h1>
            <p>@thejuniorhands</p>
            
        </section>
        <section>
            <a href="https://twitter.com/thejuniorhands" target="_blank"><i class="fab fa-twitter fa-4x"></i></a>
            
            <h1>Twitter</h1>
            <p><a href="">@thejuniorhands</a></p>
            
        </section>
        <section>
            <a href="https://www.facebook.com/Junior-Hands-Association-102088245579172" target="_blank"><i class="fab fa-facebook fa-4x"></i></a>
            
            <h1>Facebook</h1>
            <p>@thejuniorhands</p>
            
        </section>
        <div class="cont-apply">
            <h1>Want to do more than messaging?</h1>
            <h2>Apply to become a member and help us organize events. </h2>
            <form>
                <button formaction="{% url 'apply:apply' %}" >Apply</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/donate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}JHA - Donate{% endblock %}
{% block content %}
<div class="donate-body">
    <img src="../static/apprightimg.png" class="doge" alt="dog"/>
    <h1>Sorry, this page is under construction.</h1>
</div>
{% endblock %}

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>JHA - Home</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        
        <link rel="stylesheet" type="text/css" href="../static/css/style.css">
        <link rel="stylesheet" type="text/css" href="../static/css/contact.css">

    </head>
    <body>
        <!-- Nav Bar -->
        <header>


            <nav class="navbar">
                <div class="logo">
                    <img src="../static/whitered2.png" alt="logo" width="60" height="60" class="logo-img" />
                    <h1>Junior Hands Assocation </h1>
                </div>
                
                <div class="hamburger">
                    <div class="line"></div>
                    <div class="line"></div>
                    <div class="line"></div>
                </div>
                <ul class="nav-links">
                    <li><a href="{% url 'app:home' %}"
                        {% if request.path == "/" %}
                        class="current"
                        {% endif %}>Home</a></li>
                    <li><a href="{% url 'app:about' %}"
                        {% if request.path == "/about/" %}
                        class="current"
                        {% endif %}>About</a></li>
                    <li><a href="{% url 'app:contact' %}"
                        {% if request.path == "/contact/" %}
                        class="current"
                        {% endif %}>Contact</a></li>
                    <li><a href="{% url 'app:donate' %}"
                        {% if request.path == "/donate/" %}
                        class="current"
                        {% endif %}>Donate</a></li>
                    
                </ul>
            </nav>
       <!-- Hero Text -->
         <div class="text-container">
            <h1>We Are The <span>Change.</span></h1>
            <!-- <form >
                <button formaction="{% url 'apply:apply' %}" id="apply-btn">Apply Now</button>
            </form> -->
            
            
        </div>


        

        </header>
     

        <!-- mission statement  -->
        <div id="weare" class="mission">

            <h2>Who We Are</h2>
            <p>
                The Junior Hands Association is a newly formed registering 501c3 organization that’s determined to help fix the injustices in modern day education. We see deep rooted injustice in marginalized populations all around us and we hope to fix at least one aspect of that through our educational programs and services. We are resolved in our mission to foster healthy communities that always have access to the educational materials they need to prosper. By focusing on student-led activism we hope to promote ideals that linger beyond generations. The Junior Hands Association seeks to be a leading nonprofit in advocating for socioeconomic, racial, and gender equality through education platforms.
            </p>
        </div>
        <div class="help-parent" >

            <h1>Support Us</h1>
            
                <div class="you-help">
                    <a class="linkwrapper" href="{% url 'app:home' %}#upcoming">        
                        <div>
                            <section class="header">
                                <img src="../static/getInvolved.png" width="100" height="100" />
                                <h2>Get Involved</h2>

                            </section>
                                <p>The best way to get involved is to become a volunteer. By clicking this section you’ll be able to view our events and volunteer to help make our community a better place for all youth. 

                                </p>    
                        
                        </div>
                    </a>
                    <a class="linkwrapper" href="{% url 'apply:apply' %}">
                        <div>
                
                            <section class="header">
                                <img src="../static/join_us.png" width="100" height="100" />
                                <h2>Join Us</h2>

                            </section>

                                <p>Certain committed volunteers have the chance to become full members and advance to the next level by helping with planning, fundraising, and running events. To become a member, click on this section.


                                </p>    
                        
                        </div>
                    </a>
                    <a class="linkwrapper" href="{% url 'app:donate' %}">
                        <div>
                            <section class="header">
                                <img src="../static/donateicon.png" width="100" height="100" />
                                <h2>Donate</h2>

                            </section>
                                <p>Donations are essential for running our programs. All donations go straight to our cause and are solely used for the community. While our page is under construction, please email us to donate. Thank You!

                                </p>    
                        
                    </a>

            </div>      
        </div>
        <!-- Member Application Section-->
        
        <!-- mission statement -->
        <div class="parent" id="upcoming">
            <h1> Upcoming Events </h1>
            <a class="events-link" href="{% url 'app:events' %}"> See Full Events Page </a>
            <div class="upcoming">
                
                {% if events %}
                    {% for event in events %}
                   
                    <div class="event">
                        <div class="date">
                            <h2> {{event.month}}</h2>
                            <h2> {{ event.day }}</h2>
                        </div>
                        
                        <div class="info">
                            <h2 class="event-name"> {{ event.eventName }}</h2>
                            <h2> {{event.location}}</h2>
                        </div>
                    </div>
                    
                    {% endfor %}
                {% else %}
                <h1 class="no-event"> No Events </h1>
                {% endif %}

            </div>
            
        </div>
        <footer>

        
            <section class="contacts">
                
                <a href="https://www.instagram.com/thejuniorhands/" target="_blank"><img src="../static/insta.png" width="55" height="55" alt="insta"></a>
              <a href="https://twitter.com/thejuniorhands" target="_blank"><img src="../static/twitter.png" width="55" height="55" alt="twitter"></a>
              <a href="https://www.facebook.com/Junior-Hands-Association-102088245579172" target="_blank"><img src="../static/facebook.png" width="55" height="55" alt="facebook"></a>
            </section>
            <section class="links">
                <a href="{% url 'app:home' %}">HOME</a>
                <a href="{% url 'app:about' %}">ABOUT</a>
                <a href="{% url 'app:contact' %}">CONTACT</a>
            
            </section>
            <section class="section-links">
                <a href="{% url 'app:home' %}#upcoming">Upcoming</a>
                <a href="{% static 'By-laws.pdf' %}" target="_blank">By Laws</a>
                <a href="{% url 'app:contact' %}#emailus">Email</a>
                <a href="{% url 'apply:apply' %}">Apply</a>
            </section>
            <button> <a href ="#" >Donate</a></button>


            <br></br>
        </footer>
       

        <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
        <script>

            $(window).scroll(function(){
                if($(window).scrollTop() ){
                    $("nav").addClass("sticky");
                    $("a.current").addClass("current-2")
                }
                else{
                    $("nav").removeClass("sticky");
                    $("a.current").removeClass("current-2")
    
    
                }
            })
        </script>
        <script>
             const hamburger = document.querySelector('.hamburger');
             const navLinks = document.querySelector('.nav-links');
             const links = document.querySelectorAll('.nav-links li');
             const logo = document.querySelector('.logo')
             hamburger.addEventListener('click', () => {
                 navLinks.classList.toggle('open');
                 logo.classList.toggle('open');
             })
        </script>
    </body>
</html>

app/templates/volunteer.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>JHA - Volunteer</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        <link rel="stylesheet" type="text/css" href="../static/css/volunteer.css">
        <link rel="stylesheet" type="text/css" href="../static/fontawesome/css/all.min.css">
    </head>

    <body>
        <form action="" method="POST">
            <h1>The Junior Hands Association</h1>
            <h2>Volunteer Form</h2>
            {% csrf_token %}
            
            {{ form.event|add_class:"event-field" }}
            <label style="margin-left: 5%;">Event</label>
            <div>
                <section>
                    {{ form.first_name|add_class:"first-name" }}
                    <label>First Name</label>
                </section>
                <section>
                    {{ form.last_name|add_class:"last-name"}}
                    <label>Last Name</label>
                </section>
                
            </div>
            
            {{ form.v_email|add_class:"email-field"}}
            <label style="margin-left: 5%;">Email</label>
            <input class="vol-sub-btn" type="submit" value="Submit">
            {% if messages %}
            <div class="alert alert-success" role="alert" style="width: 20em;margin: 0 auto;text-align:center;">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
            {% endif %}
        </form>
        
       
    </body>
   
</html>